version: "3"

services:
  db:
    image: postgres:10
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 8001:5432
  backend:
    build: .
    env_file:
      - .env
    command: bash -c "poetry run python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  db:
  app:
