# Generated by Django 4.2.3 on 2023-07-09 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_vote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="participant",
            new_name="participants",
        ),
    ]
