# Generated by Django 4.2.3 on 2023-07-10 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0004_alter_answer_question_alter_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="invitee",
            field=models.ManyToManyField(
                related_name="quizess_invited", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
