# Generated by Django 4.2.3 on 2023-07-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_quiz_invitee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="invitee",
            new_name="invitees",
        ),
    ]
